"""
utils/pdf_generator.py
----------------------
Generates a professional Sales Order confirmation PDF with reportlab:
company header/logo, SO metadata, customer block, an itemised table with
per-line net values, a totals summary (net / GST / total) and an
"Generated by AI Agent" footer.
"""
from __future__ import annotations

import io

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle,
)

from schemas import SalesOrder

# Brand palette (enterprise blue).
BRAND = colors.HexColor("#1E3A5F")
ACCENT = colors.HexColor("#2E7D32")
LIGHT = colors.HexColor("#EEF2F7")
GREY = colors.HexColor("#6B7280")


class SalesOrderPDF:
    def __init__(self) -> None:
        self.styles = getSampleStyleSheet()
        self.styles.add(ParagraphStyle(
            "Brand", parent=self.styles["Title"], textColor=BRAND, fontSize=20,
            spaceAfter=2, alignment=0))
        self.styles.add(ParagraphStyle(
            "Sub", parent=self.styles["Normal"], textColor=GREY, fontSize=9))
        self.styles.add(ParagraphStyle(
            "H", parent=self.styles["Heading3"], textColor=BRAND, fontSize=11,
            spaceBefore=8, spaceAfter=4))
        self.styles.add(ParagraphStyle(
            "Small", parent=self.styles["Normal"], fontSize=9, leading=12))

    def build(self, so: SalesOrder) -> bytes:
        buf = io.BytesIO()
        doc = SimpleDocTemplate(
            buf, pagesize=A4,
            leftMargin=18 * mm, rightMargin=18 * mm,
            topMargin=16 * mm, bottomMargin=16 * mm,
            title=f"Sales Order {so.so_number}",
        )
        elements = []
        cur = so.currency or "INR"

        # ---- Header band ------------------------------------------------ #
        header = Table(
            [[Paragraph("AI ERP Automation", self.styles["Brand"]),
              Paragraph("<b>SALES ORDER</b>", ParagraphStyle(
                  "R", parent=self.styles["Title"], textColor=BRAND,
                  fontSize=18, alignment=2))]],
            colWidths=[100 * mm, 74 * mm],
        )
        header.setStyle(TableStyle([
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 2),
        ]))
        elements.append(header)
        elements.append(Paragraph(
            "Order-to-Cash · Automated document processing", self.styles["Sub"]))
        elements.append(Spacer(1, 6))
        elements.append(Table([[""]], colWidths=[174 * mm], style=TableStyle([
            ("LINEBELOW", (0, 0), (-1, -1), 1.4, BRAND)])))
        elements.append(Spacer(1, 8))

        # ---- Meta + customer -------------------------------------------- #
        meta = [
            ["SO Number", so.so_number, "PO Reference", so.po_number or "-"],
            ["Status", so.status, "PO Date", so.po_reference_date or "-"],
            ["Created By", so.created_by, "Created At", so.created_at],
            ["Currency", cur, "Payment Terms", so.payment_terms or "-"],
        ]
        meta_tbl = Table(meta, colWidths=[26 * mm, 61 * mm, 30 * mm, 57 * mm])
        meta_tbl.setStyle(TableStyle([
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("TEXTCOLOR", (0, 0), (0, -1), GREY),
            ("TEXTCOLOR", (2, 0), (2, -1), GREY),
            ("FONTNAME", (1, 0), (1, -1), "Helvetica-Bold"),
            ("FONTNAME", (3, 0), (3, -1), "Helvetica-Bold"),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ("TOPPADDING", (0, 0), (-1, -1), 2),
        ]))
        elements.append(meta_tbl)
        elements.append(Spacer(1, 6))

        elements.append(Paragraph("Sold To", self.styles["H"]))
        elements.append(Paragraph(
            f"<b>{so.customer_name}</b> ({so.customer_code})<br/>"
            f"{so.shipping_address or 'Address on file'}<br/>"
            f"GSTIN: {so.gst_number or '-'}",
            self.styles["Small"]))
        elements.append(Spacer(1, 8))

        # ---- Items table ------------------------------------------------ #
        elements.append(Paragraph("Order Items", self.styles["H"]))
        head = ["#", "Material", "Description", "Qty", f"Unit ({cur})", f"Net ({cur})"]
        rows = [head]
        for i, it in enumerate(so.items, start=1):
            rows.append([
                str(i), it.material, it.description, f"{it.qty:g}",
                f"{it.unit_price:,.2f}", f"{it.net_value:,.2f}",
            ])
        items_tbl = Table(rows, colWidths=[8 * mm, 26 * mm, 74 * mm, 16 * mm, 24 * mm, 26 * mm])
        items_tbl.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), BRAND),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 8.5),
            ("ALIGN", (3, 0), (-1, -1), "RIGHT"),
            ("ALIGN", (0, 0), (0, -1), "CENTER"),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, LIGHT]),
            ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#D0D7DE")),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ]))
        elements.append(items_tbl)
        elements.append(Spacer(1, 8))

        # ---- Totals ----------------------------------------------------- #
        totals = [
            ["Net Value", f"{so.net_value:,.2f} {cur}"],
            [f"GST @ {so.tax_rate * 100:.0f}%", f"{so.tax_amount:,.2f} {cur}"],
            ["Total", f"{so.total_value:,.2f} {cur}"],
        ]
        totals_tbl = Table(totals, colWidths=[40 * mm, 44 * mm], hAlign="RIGHT")
        totals_tbl.setStyle(TableStyle([
            ("FONTSIZE", (0, 0), (-1, -1), 9.5),
            ("ALIGN", (1, 0), (1, -1), "RIGHT"),
            ("LINEABOVE", (0, -1), (-1, -1), 1, BRAND),
            ("FONTNAME", (0, -1), (-1, -1), "Helvetica-Bold"),
            ("TEXTCOLOR", (0, -1), (-1, -1), ACCENT),
            ("TOPPADDING", (0, 0), (-1, -1), 3),
        ]))
        elements.append(totals_tbl)
        elements.append(Spacer(1, 16))

        # ---- Footer ----------------------------------------------------- #
        elements.append(Table([[""]], colWidths=[174 * mm], style=TableStyle([
            ("LINEBELOW", (0, 0), (-1, -1), 0.6, colors.HexColor("#D0D7DE"))])))
        elements.append(Spacer(1, 4))
        elements.append(Paragraph(
            "This is a system-generated Sales Order confirmation. "
            "<b>Generated by AI Agent</b> — no manual order entry involved.",
            self.styles["Sub"]))

        doc.build(elements)
        return buf.getvalue()
